name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 3
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"
  RSVIM_LOG: "trace"
  RUST_BACKTRACE: "full"
  RUSTC_LOG: "rustc_codegen_ssa::back::link=info"
jobs:
  unit_test:
    name: Unit Test
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, macos-14, macos-13, windows-2022]
    runs-on: ${{ matrix.os }}
    env:
      RUSTC_WRAPPER: "sccache"
      SCCACHE_GHA_ENABLED: "true"
    steps:
      - uses: Swatinem/rust-cache@v2
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: Install Rust
        run: |
          rustup update --no-self-update stable
          rustup default stable
          rustup component add --toolchain stable rust-src clippy llvm-tools
      - uses: actions/checkout@v5
      - name: Cargo test
        run: |
          cargo test --verbose --features 'default v8_unsafe_use_unprotected_platform' -p rsvim_core
